language: cpp
env:
  global:
  - FORCE_INSTALL=1
  - BUILD_UTILITIES=1
matrix:
  include:
  - os: osx
    name: Build
    osx_image: xcode10.2
    compiler: clang
    script:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - "./macbuild.tool"
    deploy:
      provider: releases
      skip_cleanup: true
      file:
      - Binaries/RELEASE/*.zip
      - Binaries/DEBUG/*.zip
      file_glob: true
      draft: true
      branches:
        only:
        - weird-ioread-bug

  - os: osx
    name: Analyze Coverity
    osx_image: xcode10.2
    compiler: clang
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - curl -Ls https://entrust.com/root-certificates/entrust_l1k.cer -o ~/entrust_l1k.crt || exit 1
    - curl -LS https://curl.haxx.se/ca/cacert.pem -o ~/cacert.pem || exit 1
    - cat ~/entrust_l1k.crt >> ~/cacert.pem || exit 1
    - echo "cacert=\"$HOME/cacert.pem\"" > ~/.curlrc || exit 1
    - echo "ca_certificate=$HOME/cacert.pem" > ~/.wgetrc || exit 1
    script:
    - echo "This script runs coverity..."

deploy:
  password:
    secure: 0b7PKmR+d+DxVWiqXe7OPm3sAPRZ8AJF6J4YcLFWhNsb003J6pk3s78vDP0+EHqolll21AJmbXr1hORXmkY3aGIGwunBSbvxJQTXfQuvMvBWdXM0CDYxnq4eAt2N4e34DA8siZx/yaUdHiI+twPa3Vx7xOtAUAtUjyy/i+DKyQtCHCij5oPy4lP4SCYwzDH7NlyOzK+00vFam0dTsqT9qQPGcRgOiXE5J+t9iJk4r0he6e/hKRRuPHfC3vYixDABQKQKiIcmYcUtddXojzREdsA0cjyQrrYANI6w+BaJwtNL52GD1+RaNFPQrCzZ59EPWWtkQFY6BixFI0h5zv6M5qRDkrIQL/xzOkFEU9i7Ooe+lLB66ESxpqjezNSgKzgtz8Zhnd9nBLIlEVRFGuQ1kpH6vpS5r5sL1CDpKUN9KLaUl6Qq99KqWfPh5nd7gU8F6DsELi3cnX90MiX/7pU1cFnRJCGBT/yoUIrpcC7Cd+oJzvbeeefYyfXZ0EhNCOgJfnrBeJeQUjNBZC9YtyU8ykAA+nJUBkhAchah/YKShlsSxki5K8mBoyWKwFhUdibDd5r5blzaLcD2Nfqs28YpGYc2DccxvBNx+Pewrsc0R4dGMmO76/baAFNIEaXy268Z4+xAP5IAOuD54qpVMERT/QpbM164F6jeX7NN5K08u6E=
