language: cpp
env:
  global:
  - FORCE_INSTALL=1
  - BUILD_UTILITIES=1
matrix:
  include:
  - os: osx
    name: Build
    osx_image: xcode10.2
    compiler: clang
    script:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - "./macbuild.tool"
    deploy:
      provider: releases
      skip_cleanup: true
      file:
      - Binaries/RELEASE/*.zip
      - Binaries/DEBUG/*.zip
      file_glob: true
      draft: true
      on:
        all_branches: true
      api_key:
        secure: BzZ2GvTpsjVeM5Evhr+gZ9CRDPJSAdeNzyvoCMr2pJjUkXuwak0k91xh+kH+7nvVtAJi8Dso2XcJ9GvaL/TEGEmAnhyYv3cITniYhhBOw/Tx3HuCne2o3Dg7qDXer1H8yPANvxQodB4FMV94IFltrbxKnYkNwOvRZLJhqGiRgnILQt+QkBr+WdZioaoeqbc/5//IF2zc4g1lOLgYYsMAoc3Dlx7zG+K3uQJXIl/5toFLfrsaCl9LAl7eqhIfzIURcAju3ioBthiF7N8cNr55ZDt1PC44IvsrnXlhUvFJPoWD4oho5EORy+t9tALhlSJx961QpWntoJxyBrADvxgm6u47+6q4feS6vMeRhJapqWoJzGyKpIeaO4nReDN302Rf3fzlKtpwAKOdDQySH/qr5pTadkW4o6L++gnqOg8cyaCjTZi85iIeCxRb9H3CmUMP4LWEZUrRTG9UxpSelI2LHicYuGpTQ/m8xYUd1PYjPdZ8/BQB2yZMP5M432TLnl69Br0r2/7izQJDq4Dt3epKYbeWs9eJo1vhPaHCUYudBQ026Ti/sWaH6lOeDQ6vh64Fa7oK/67l+omi/r0k0CJ3V5grMVz/nk5EF+9SAJWf0PjVak50CiDtcZfVCn2sSYimSBhuR6U3zY5zcugVLzwgSWOB3EIEunP9cdddLZeBFVU=
  - os: osx
    name: Analyze Coverity
    osx_image: xcode10.2
    compiler: clang
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
    - curl -Ls https://entrust.com/root-certificates/entrust_l1k.cer -o ~/entrust_l1k.crt
      || exit 1
    - curl -LS https://curl.haxx.se/ca/cacert.pem -o ~/cacert.pem || exit 1
    - cat ~/entrust_l1k.crt >> ~/cacert.pem || exit 1
    - echo "cacert=\"$HOME/cacert.pem\"" > ~/.curlrc || exit 1
    - echo "ca_certificate=$HOME/cacert.pem" > ~/.wgetrc || exit 1
    script:
    - echo "This script runs coverity..."
